### ISSUE TITLE
Automaticly open c:\bios directory (if present) when flashing BIOS file to bank

### ISSUE THREAD

**Issue by TheRealNextria** [Team-Resurgent/PrometheOS-Firmware#1]
Is it possible to automaticly open c:\bios directory (if present) when flashing BIOS file to bank

**Comment by HoRnEyDvL** [comment]
Upon discussion, and community feedback the file browser method is the best for all as it allows everyone to browse to location they have stored Bios. 

For example some have bios in E or F partition or in different folders.

:)
