### ISSUE TITLE
v1.02 gets no image output if console is turned on by using eject button

### ISSUE THREAD

**Issue by PrimeRetroGamer** [Team-Resurgent/PrometheOS-Firmware#2]
Update v1.02 gets no image output if console is turned on by using eject button. (Most of the time.)
Reverted back to v1.01 and it is working as expected.

Some notes, that might be relevant:
- 1.6 motherboard;
- OpenXenium modchip;
- component cables;
- removed DVD drive.

Turning console on by using power button seems to work fine.

**Comment by HoRnEyDvL** [comment]
Should be fix with 1.1.0 release.

Please confirm.

**Comment by PrimeRetroGamer** [comment]
> Should be fix with 1.1.0 release.
> 
> Please confirm.

Seems to be fixed! 15 out of 15 successful boots with image output using the eject button.

**Comment by HoRnEyDvL** [comment]
Issue Fixed. Ticket Closed
