### ISSUE TITLE
v1.1.1 apparently does not access Harddrive

### ISSUE THREAD

**Issue by DeBuGWoLf** [Team-Resurgent/PrometheOS-Firmware#3]
- Open Xenium Modchip
- 1.6 Xbox
- SATA HDD

Shows blank directory via FTP, Skins and Soundpacks not showing up.

(v1.1.1 is the only version i tried)

**Comment by HoRnEyDvL** [comment]
Prometheos folder should now be in the root of e:/ not c: anymore.

**Comment by Andr-Zero** [comment]
Double check your HDD is working correctly. Done several 1.6s with IDE, SATA, HDD/SDDs. Any time something like that was an error on my part.

**Comment by DeBuGWoLf** [comment]
Ok so i tried placing the PrometheOS folder in e:/ still without success(readme.nfo tells you to place it in c:/,
Yes my harddrive is working its also detected by PrometheOS.

Only thing that i could think of if its a problem on my side is my IDE to SATA adapter. Its pretty slow witch also makes IGR crash my console, could this cause PrometheOS to not function properly?

**Comment by DeBuGWoLf** [comment]
closed since it is most likly my faul..
